### ISSUE TITLE
Error get ticket function

### ISSUE THREAD

**Issue by nschaefer1211** [chrisumphlett/zdeskR#1]
Hi, 

when running the following command: 

_zdeskR::get_tickets(email_id, token, subdomain,
                           start_time = "2021-07-31 00:00:00", end_time = "2021-08-01 23:59:59")_

I got the following error: **Error: Can't combine `..1$30196289` \<character> and `..142$30196289` \<logical>.**
The rlang::last_error() backtrace gave the following:

Backtrace:
 1. zdeskR::get_tickets(...)
 2. purrr::map_dfr(seq_len(nrow(tickets)), pivot_data_frame)
 3. dplyr::bind_rows(res, .id = .id)
 4. vctrs::vec_rbind(!!!dots, .names_to = .id)
 6. vctrs::vec_default_ptype2(...)
 7. vctrs::stop_incompatible_type(...)
 8. vctrs:::stop_incompatible(...)
 9. vctrs:::stop_vctrs(...)

Does anybody know what the issue here is?

**Comment by chrisumphlett** [comment]
Possible something to do with custom fields, those values look like field id's.

The general error of "can't combine [type a] and [type b]" is because when `purrr::map_dfr` is looping over all the results and combining them into a single data frame, there is a column (30196289 I think) which in one df is a character and the other a logical type. The logical probably because it's all `NA` and R couldn't detect the actual type so it gets logical by default.

Do you have the access and knowledge to look into your zendesk configuration and find out if 30196289 is a field id, and what that field is?

**Comment by nschaefer1211** [comment]
Thank you so much for your prompt reply! 
I think you are on the right track. I checked, 30196289 is a field id. It is a checkbox whether to send an email or not. So the value should always either be TRUE or FALSE. Does that help?

**Comment by chrisumphlett** [comment]
Here is what I think is happening
![image](https://user-images.githubusercontent.com/7210482/128559773-4d347027-8a40-4ecc-b87e-adf0d02aeb48.png)

Unfortunately I think I can diagnose the problem well but I don't know how to solve it. Converting _every_ custom field column to character would probably solve the problem but might cause other undesirable issues (slow things down and lead to non-character columns being character and force the user to convert it back).

Maybe only converting logical columns to character would be better? But even then, that could result in an error if the column was truly numeric.

I have another function that you're likely going to want to use called `get_custom_fields()`. This is useful to make sense of the data from `get_tickets()` if there are a lot of custom fields. Perhaps there would be some way to use the custom field data and optionally interject it into the `get_tickets()` process. EG, you could select all of the custom field Ids that you want to keep and specify the data type. That would be slick, but I don't have time to work on that right now.

I think my preference in the short term to help solve your problem would be to allow the user to _drop_ undesired columns. Without more users of the package to pitch in about how they use it and what is better long-term, I can only speculate. What do you think of that? There would be a new function input, you'd put "30196289" there. Then run it again. If another column fails, you'd have to add that as well.

If you don't like that you could fork the package and do the conversion of everything to character but I wouldn't want to merge that back in, at least not yet. I would not like it for our data.

**Comment by nschaefer1211** [comment]
I think you hit the nail on the head with your analysis of the situation. I also don't know how to fix this problem easily. However, your short-term fix with allowing the user to drop undesired columns should work for me. This drop argument should allow for multiple columns to be selected, if possible, as I have another checkbox. 
Thank you so much for taking the time and effort to find a solution!!

**Comment by chrisumphlett** [comment]
I pushed a change to a new branch for you to try out. I have tested and it works for me, see sample code below. 

`tix2 <- get_tickets(email_id = email_id, token = token, subdomain = subdomain,
                    start_time = "2021-08-11", end_time = "2021-08-11",
                    remove_cols = c("23798518", "55790847"))`

You can install this from GH like this: `remotes::install_github("chrisumphlett/zdeskR@remove-cols-from-tickets")`.

**Comment by nschaefer1211** [comment]
It worked, thank you so much!! I will close this issue soon but while I have your attention, I was wondering if it would be possible to also include arguments start_time and end_time in the get_all_ticket_metrics()-function. That would be of great help to me.

**Comment by chrisumphlett** [comment]
Great. I made a new issue for your latter comment, see response there. 

I am going to leave this open a bit longer and test it on my end with our code that gets ticket data daily and make sure there are no problems there. Then I'll merge it in with the master and it can be installed as the regular dev version. I won't push that to CRAN right now.

**Comment by nschaefer1211** [comment]
Sounds great, thanks again!
